### ISSUE TITLE
Upgrade waf to python3

### ISSUE THREAD

**Issue by audebert** [prologin/stechec2#15]
> ###### Originally posted 2014-05-02 21:30 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

It currently depends on python2, and fails on loading unitttest_gtest:

    Traceback (most recent call last):
      File "/usr/lib/waf/.waf3-1.7.15-af648a117ce281087d8735a3803e0ebf/waflib/Scripting.py", line 97, in waf_entry_point
        run_commands()
      File "/usr/lib/waf/.waf3-1.7.15-af648a117ce281087d8735a3803e0ebf/waflib/Scripting.py", line 149, in run_commands
        parse_options()
      File "/usr/lib/waf/.waf3-1.7.15-af648a117ce281087d8735a3803e0ebf/waflib/Scripting.py", line 127, in parse_options
        Context.create_context('options').execute()
      File "/usr/lib/waf/.waf3-1.7.15-af648a117ce281087d8735a3803e0ebf/waflib/Options.py", line 134, in execute
        super(OptionsContext,self).execute()
      File "/usr/lib/waf/.waf3-1.7.15-af648a117ce281087d8735a3803e0ebf/waflib/Context.py", line 84, in execute
        self.recurse([os.path.dirname(g_module.root_path)])
      File "/usr/lib/waf/.waf3-1.7.15-af648a117ce281087d8735a3803e0ebf/waflib/Context.py", line 125, in recurse
        user_function(self)
      File "/root/stechec2/wscript", line 18, in options
        opt.load('unittest_gtest')
      File "/usr/lib/waf/.waf3-1.7.15-af648a117ce281087d8735a3803e0ebf/waflib/Context.py", line 78, in load
        module=load_tool(t,path)
      File "/usr/lib/waf/.waf3-1.7.15-af648a117ce281087d8735a3803e0ebf/waflib/Context.py", line 313, in load_tool
        __import__(d)
    TypeError: source code string cannot contain null bytes

**Comment by seirl** [comment]
> ###### Originally posted 2015-10-13 12:07 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

We can use that PR: https://github.com/tanakh/waf-unittest/pull/18

(We don't really need to wait until it's merged upstream since the binary is in our repository.)

**Comment by seirl** [comment]
> ###### Originally posted 2015-10-14 01:37 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Fixed by 3744dd84a1d3
